Repository redhat-appstudio/managed-gitops, pull requests merged in 2022-10, with the labels that each got.

#233 Fix PromotionRun E2E test.
  tests-e2e/core/applicationpromotionrun_controller_test.go
Labels: lgtm, approved

#243 Split appstudio-controller and backend/cluster-agent controllers
  appstudio-shared/config/kcp-new/apiexport_gitopsrvc_appstudioshared.yaml
  appstudio-shared/config/kcp-new/kustomization.yaml
  backend-shared/config/kcp-new/apiexport_gitopsrvc_backendshared.yaml
  backend-shared/config/kcp-new/apiresourceschema_gitopsrvc_backendshared.yaml
  backend-shared/config/kcp-new/kustomization.yaml
  manifests/controller-deployments/appstudio-controller/kustomization.yaml
  manifests/controller-deployments/appstudio-controller/managed-gitops-appstudio-controller-deployment.yaml
  manifests/controller-deployments/kustomization.yaml
  manifests/kcp/appstudio-controller/kustomization.yaml
  manifests/kcp/kustomization.yaml
Labels: approved

#245 Fixes E2E: AppStudio controller manifest PATH
  Makefile
Labels: lgtm, approved

#244 Disable appstudio logic which create a GitOpsDeployment for every AppStudio Application
  appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
Labels: lgtm

#253 Check if the APIs are synced in a workspace
  kcp/utils.sh
  kcp/virtual-workspace.sh
Labels: lgtm
