Repository redhat-appstudio/managed-gitops, pull requests merged in 2022-06, with the labels that each got.

#138 Add OWNERS file for ci
  OWNERS
Labels: lgtm

#145 Update appstudio-controller examples, and instructions
  appstudio-controller/README.md
  appstudio-controller/examples/README.md
  appstudio-controller/examples/application.yaml
  appstudio-controller/examples/appstudio-application-example.yaml
  appstudio-controller/examples/component-demo.yaml
Labels: approved

#149 Fix missing CRD in Makefile, update Repository Credentials Role, fix backend time format
  Makefile
  backend/Makefile
  backend/routes/router.go
  manifests/backend-rbac/managed-gitops-backend-manager-role.yaml
Labels: lgtm, approved

#150 Update to latest Application/Component resources from HAS
  Makefile
  appstudio-controller/go.mod
  appstudio-controller/go.sum
  tests-e2e/go.mod
  tests-e2e/go.sum
Labels: lgtm, approved

#139 Write error tests for operation_event_loop.go
  backend-shared/config/db/queries.go
  cluster-agent/controllers/managed-gitops/eventloop/eventloop_suite_test.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
Labels: lgtm, approved

#153 Fix CI: Switch to using migration to initialize the database scheme when running on k8s, increase timeouts
  create-dev-env.sh
Labels: lgtm, approved, do-not-merge/hold

#160 Update appstudio controller RBAC to add Environment API
  manifests/appstudio-controller-rbac/appstudio-controller-rbac.yaml
Labels: approved, do-not-merge/hold

#164 Add chetan to the list of reviewers for the openshift-ci
  OWNERS
Labels: lgtm, approved

#163 Update manifests: update health ports, and add zap logging parameter
  manifests/managed-gitops-appstudio-controller-deployment.yaml
  manifests/managed-gitops-backend-deployment.yaml
  manifests/managed-gitops-clusteragent-deployment.yaml
Labels: lgtm, approved

#159 Create a new token secret for service account if the default secret is absent
  backend-shared/util/service_account.go
  backend-shared/util/service_account_test.go
Labels: lgtm, approved

#167 Add create-db target to use it with openshift-ci setup
  Makefile
Labels: lgtm, approved
