Repository redhat-appstudio/managed-gitops, pull requests merged in 2022-08, with the labels that each got.

#189 Update backend/appstudio-controller K8s manifests
  manifests/managed-gitops-appstudio-controller-deployment.yaml
  manifests/managed-gitops-backend-deployment.yaml
Labels: approved

#190 fix: type 256i -> 256Mi
  manifests/managed-gitops-appstudio-controller-deployment.yaml
Labels: lgtm

#192 Increase memory limit of backend controller
  manifests/managed-gitops-backend-deployment.yaml
Labels: approved

#193 Add the `conditions` status field to Snapshot
  appstudio-shared/apis/appstudio.redhat.com/v1alpha1/applicationsnapshot_types.go
  appstudio-shared/apis/appstudio.redhat.com/v1alpha1/zz_generated.deepcopy.go
  appstudio-shared/config/crd/bases/appstudio.redhat.com_applicationsnapshots.yaml
  appstudio-shared/manifests/appstudio-shared-customresourcedefinitions.yaml
Labels: lgtm, approved

#201 Refactor repocred tests to use operations.CreateOperation()
  cluster-agent/controllers/managed-gitops/eventloop/repocred_test.go
Labels: lgtm

#202 [DEVHAS-148] Add CommitID field to ApplicationSnapshotEnvironmentBinding status
  appstudio-shared/apis/appstudio.redhat.com/v1alpha1/applicationsnapshotenvironmentbinding_types.go
  appstudio-shared/config/crd/bases/appstudio.redhat.com_applicationsnapshotenvironmentbindings.yaml
  appstudio-shared/manifests/appstudio-shared-customresourcedefinitions.yaml
Labels: lgtm, approved

#203 :recycle: Use any instead of interface{}
  backend-shared/apis/managed-gitops/v1alpha1/mocks/cr-client.go
  backend-shared/apis/managed-gitops/v1alpha1/mocks/status-writer.go
  backend-shared/apis/managed-gitops/v1alpha1/mocks/structs/gitopsdeployment.go
  backend-shared/config/db/utils.go
  backend-shared/config/db/utils_test.go
  backend-shared/util/log.go
  backend-shared/util/task_retry_loop.go
  backend-shared/util/test_task_retry_loop_test.go
  backend/condition/mocks/conditions.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/workspace_event_loop.go
  backend/eventloop/workspace_resource_event_loop.go
  backend/main.go
  backend/util/createHook.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
  cluster-agent/controllers/managed-gitops/eventloop/repocred.go
  cluster-agent/utils/argocd_login_credentials.go
  cluster-agent/utils/mocks/ApplicationServiceClient.go
  cluster-agent/utils/mocks/SessionServiceClient.go
  cluster-agent/utils/mocks/SettingsServiceClient.go
  cluster-agent/utils/mocks/VersionServiceClient.go
Labels: lgtm, approved
