Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-02, with the labels that each got.

#333 Update request/limits for backend and cluster-agent components, for Stonesoup
  backend/config/manager/manager.yaml
  cluster-agent/config/manager/manager.yaml
  manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
Labels: approved

#334 Add printcolumn tags for sync and health status
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_types.go
  backend-shared/config/crd/bases/managed-gitops.redhat.com_gitopsdeployments.yaml
Labels: lgtm

#336 Add Makefile target to run lint checks for all components
  Makefile
Labels: lgtm

#331 Re-removing the gitOpsDeployment creation logic for Applications
  appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
  tests-e2e/core/appstudio_application_test.go
Labels: lgtm

#337 Fix test race condition in SnapshotEnvironmentBinding E2E test
  tests-e2e/core/snapshotenvironmentbinding_test.go
Labels: approved

#343 Fix gosec issues by handling error in defer
  backend/routes/webhooks/webhooks.go
  cluster-agent/utils/argocd_login_credentials.go
Labels: lgtm

#344 Add Namepaces to appstudio-controller role
  appstudio-controller/config/rbac/role.yaml
  appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
Labels: approved

#346 Add kustomization.yaml for each dashboard target: stonesoup and local dev
  manifests/base/monitoring/grafana-dashboards/README.md
  manifests/base/monitoring/grafana-dashboards/managed-gitops/gitops-dashboard.json
  manifests/base/monitoring/grafana-dashboards/managed-gitops/kustomization.yaml
  manifests/base/monitoring/grafana-dashboards/regenerate-stonesoup-dashboard.sh
  manifests/base/monitoring/grafana-dashboards/stonesoup/gitops-dashboard.json
  manifests/base/monitoring/grafana-dashboards/stonesoup/kustomization.yaml
Labels: approved

#349 Add an exported version of the stonesoup dashboard from Stonesoup Staging cluster
  manifests/base/monitoring/grafana-dashboards/stonesoup-new/gitops-dashboard.json
  manifests/base/monitoring/grafana-dashboards/stonesoup-new/kustomization.yaml
Labels: approved

#351 Remove temporary Grafana dashboard files
  manifests/base/monitoring/grafana-dashboards/stonesoup-new/gitops-dashboard.json
  manifests/base/monitoring/grafana-dashboards/stonesoup-new/kustomization.yaml
Labels: approved

#352 remove workflow to sync branches
  .github/workflows/sync-branch.yml
Labels: lgtm

#362 STONEBLD-777 - tekton-ci: update bundle
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm, approved

#358 Tests-e2e GitOpsDeployment fixture function should update spec, not status
  tests-e2e/fixture/gitopsdeployment/fixture.go
Labels: lgtm, approved

#363 Add component-based GitOps repo to test data
  resources/test-data/README.md
  resources/test-data/component-based-gitops-repository/README.md
  resources/test-data/component-based-gitops-repository/components/componentA/base/deployment-sample-workload.yaml
  resources/test-data/component-based-gitops-repository/components/componentA/base/kustomization.yaml
  resources/test-data/component-based-gitops-repository/components/componentA/base/route-sample-workload.yaml
  resources/test-data/component-based-gitops-repository/components/componentA/base/service-sample-workload.yaml
  resources/test-data/component-based-gitops-repository/components/componentA/overlays/dev/kustomization.yaml
  resources/test-data/component-based-gitops-repository/components/componentA/overlays/staging/kustomization.yaml
  resources/test-data/component-based-gitops-repository/components/componentB/base/deployment-sample-workload.yaml
  resources/test-data/component-based-gitops-repository/components/componentB/base/kustomization.yaml
  resources/test-data/component-based-gitops-repository/components/componentB/base/route-sample-workload.yaml
  resources/test-data/component-based-gitops-repository/components/componentB/base/service-sample-workload.yaml
  resources/test-data/component-based-gitops-repository/components/componentB/overlays/dev/kustomization.yaml
  resources/test-data/component-based-gitops-repository/components/componentB/overlays/staging/kustomization.yaml
Labels: lgtm, approved

#361 appstudio-controller tests fail on Mac Arm64 (#433)
  appstudio-controller/Makefile
Labels: lgtm, ok-to-test
