Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-05, with the labels that each got.

#444 log refinement to ADR6.
  appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/devsandbox_deployment_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/snapshot_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
  appstudio-controller/main.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_webhook.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_webhook.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_webhook.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentsyncrun_webhook.go
  backend-shared/db/util/utils.go
  backend-shared/util/gitopserrors/gitops_errors.go
  backend-shared/util/log/log.go
  backend-shared/util/operations/types.go
  backend-shared/util/service_account.go
  backend-shared/util/task_retry_loop.go
  backend-shared/util/util.go
  backend/controllers/managed-gitops/gitopsdeployment_controller.go
  backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller.go
  backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller.go
  backend/controllers/managed-gitops/gitopsdeploymentsyncrun_controller.go
  backend/controllers/managed-gitops/secret_controller.go
  backend/eventloop/application_event_loop/application_event_loop.go
  backend/eventloop/application_event_loop/application_event_runner.go
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/application_event_loop/application_event_runner_syncruns.go
  backend/eventloop/controller_event_loop.go
  backend/eventloop/db_metrics.go
  backend/eventloop/db_reconciler.go
  backend/eventloop/preprocess_event_loop/preprocess_event_loop.go
  backend/eventloop/repocred_reconciler.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/workspace_event_loop.go
  backend/eventloop/workspace_resource_event_loop.go
  backend/main.go
  cluster-agent/controllers/argoproj.io/application_controller.go
  cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_cr_metrics.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
  cluster-agent/controllers/managed-gitops/eventloop/repocred.go
  cluster-agent/controllers/managed-gitops/operation_controller.go
  cluster-agent/controllers/util.go
  cluster-agent/metrics/argocd/argocd_metrics.go
  cluster-agent/utils/argocd_create.go
  cluster-agent/utils/argocd_login_credentials.go
Labels: lgtm

#445 Fix comparison race condition in SnapshotEnvironmentBinding E2E tests
  tests-e2e/core/snapshotenvironmentbinding_test.go
  tests-e2e/fixture/binding/fixture.go
Labels: lgtm, approved

#449 Update appstudio-controller container memory limit
  manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
Labels: approved

#446 Add port-forward loop
  scripts/openshiftci-presubmit-e2e-tests.sh
Labels: lgtm, approved

#453 Improve error message when ServiceAccount doesn't have needed roles
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
Labels: lgtm, approved

#454 Update error message to indicate that kubeconfig must have a token
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
Labels: lgtm, approved

#461 Add new tekton PipelineRun to build from release branch
  .tekton/push-release-summit-2023.yaml
Labels: approved

#468 Temporarily disable infra-deployments repo update
  .tekton/push.yaml
Labels: approved

#438 Update code to remove a single 'gitops-service-argocd' Argo CD namespace
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/application_event_loop/application_event_runner_syncruns.go
  backend/eventloop/eventlooptypes/types.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/managed-gitops/operation_controller.go
  cluster-agent/metrics/argocd/argocd_metrics.go
Labels: lgtm, approved

#463 Remove references to KUBECONFIG
  Makefile
  cluster-agent/Makefile
Labels: lgtm

#466 Remove unused ApiExport references
  appstudio-controller/main.go
  backend-shared/util/manager.go
  backend-shared/util/manager_test.go
  backend/eventloop/controller_event_loop.go
  backend/eventloop/preprocess_event_loop/preprocess_event_loop.go
  backend/eventloop/workspace_event_loop.go
  backend/main.go
Labels: lgtm, approved

#474 Re-enable build and push to infra-deployment repo on main branch
  .tekton/push-release-summit-2023.yaml
  .tekton/push.yaml
Labels: approved

#462 Environment CR webhook validation.
  appstudio-controller/config/webhook/manifests.yaml
  appstudio-controller/go.mod
  appstudio-controller/go.sum
  appstudio-controller/main.go
  manifests/base/crd/overlays/local-dev/kustomization.yaml
  tests-e2e/appstudio/webhook_test.go
  tests-e2e/go.mod
  tests-e2e/go.sum
Labels: lgtm, approved

#470 Fix the placement of the error parameter
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
Labels: lgtm, approved
