Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-08, with the labels that each got.

#589 Fix ginkgolinter ci check failures
  backend/eventloop/application_event_loop/application_event_loop_test.go
Labels: lgtm, approved

#590 Update .tekton YAML based on release-service repo
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm, approved

#587 Set codecov to block PRs if they decrease coverage
  .codecov.yml
Labels: lgtm

#588 Use WithCallDepth in LogAPIResourceChangeEvent
  backend-shared/util/log/log.go
Labels: lgtm, approved

#592 Add additional test-only files to .codecov.yml ignore list
  .codecov.yml
Labels: lgtm, approved

#603 Don't use variable to specify FROM image in Dockerfiles
  Dockerfile
  Dockerfile.ci
Labels: lgtm

#605 Allow self-signed certificates in DT provisioner, on dev/test envs
  manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml
Labels: approved

#593 chore: Delete unused retrieve_metrics.go
  cluster-agent/utils/retrieve_metrics.go
Labels: lgtm, approved

#608 Prevent deletion of non-orphaned Argo CD deployed resources
  Makefile
  backend-shared/util/argocd/util.go
  backend-shared/util/argocd/util_test.go
  backend/eventloop/cluster_reconciler.go
  backend/eventloop/cluster_reconciler_test.go
Labels: lgtm, approved

#613 Fix duplicate dashboard ID
  manifests/base/monitoring/grafana-dashboards-new/gitops-dashboard.json
Labels: approved

#602 fix: Invalid cluster credentials error is logged with ERROR.
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/workspace_resource_event_loop.go
  backend/eventloop/workspace_resource_event_loop_test.go
Labels: lgtm

#609 Improve test coverage of DeleteArgoCDApplication in cluster-agent (#700)
  cluster-agent/controllers/util.go
  cluster-agent/controllers/util_test.go
Labels: lgtm

#611 Improve test coverage of backend pt1
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
Labels: lgtm

#616 Move Appstudio Environment E2E tests from core folder to appstudio folder
  tests-e2e/appstudio/environment_test.go
Labels: lgtm, approved

#606 Update .ci base-image Dockerfile go version
  .ci/base-image/Dockerfile
Labels: lgtm, approved

#619 chore: improve test coverage for backend-shared.
  backend-shared/db/apicrtodatabasemapping_test.go
  backend-shared/db/application_test.go
  backend-shared/db/clusteraccess_test.go
  backend-shared/db/clustercredentials_test.go
  backend-shared/db/clusteruser_test.go
  backend-shared/db/gitopsenginecluster_test.go
  backend-shared/db/kubernetesresourcetodbresourcemapping_test.go
  backend-shared/db/managedenvironment_test.go
  backend-shared/db/operations_test.go
  backend-shared/db/repo_cred_test.go
  backend-shared/db/syncoperation_test.go
Labels: lgtm

#629 Fix panic in isManagedEnvironmentConnectionUserError
  backend/eventloop/workspace_resource_event_loop.go
  backend/eventloop/workspace_resource_event_loop_test.go
Labels: approved

#623 chore: improve test coverage.
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_types_test.go
Labels: lgtm
