Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-09, with the labels that each got.

#610 Fix initial set of kubelinter warnings
  manifests/base/postgresql-staging/postgresql-staging.yaml
  manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml
Labels: lgtm, approved

#630 E2E tests for SEB webhook
  appstudio-controller/go.mod
  appstudio-controller/go.sum
  manifests/base/crd/overlays/local-dev/kustomization.yaml
  tests-e2e/fixture/k8s/fixture.go
  tests-e2e/go.mod
  tests-e2e/go.sum
  utilities/load-test/go.mod
  utilities/load-test/go.sum
Labels: lgtm, approved

#624 Tests for application_info_cache.go in cluster-agent component (#701)
  cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache_suite_test.go
  cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache_test.go
Labels: lgtm

#628 GITOPSRVCE-742: ensure operation is always created when appproject DB is updated
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
  tests-e2e/core/gitopsdeployment_test.go
  tests-e2e/fixture/fixture.go
Labels: approved

#625 Improve test coverage of workspace event loop
  backend/eventloop/workspace_event_loop_test.go
Labels: lgtm

#644 Move sanity test before the log statement to avoid panic in 'workspace_event_loop_test' unit tests
  backend/eventloop/workspace_event_loop.go
Labels: approved

#643 GITOPSRVCE-56: Enable AppProject isolation feature flag via environment variable
  backend/config/manager/manager.yaml
  cluster-agent/config/manager/manager.yaml
  tests-e2e/Makefile
Labels: approved

#650 Fix invalid whitespace on tests-e2e/Makefile
  tests-e2e/Makefile
Labels: lgtm, approved

#615 Improve test coverage of backend pt2
  backend/eventloop/repocred_reconciler_test.go
Labels: lgtm

#621 Add unit tests for getDBOperationForEvent function in cluter-agent
  .codecov.yml
  backend-shared/util/mocks/mock_client.go
  backend-shared/util/mocks/mock_database_queries.go
  cluster-agent/controllers/managed-gitops/eventloop/mocks/log_sink_mock.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
Labels: lgtm, approved

#631 chore: improve test coverage.
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
Labels: lgtm

#654 Restrict repo server parallelism and git/kustomize run time
  manifests/base/gitops-service-argocd/base/argo-cd.yaml
Labels: approved
