Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-11, with the labels that each got.

#703 fix intermittent E2E test failure in 'argocd_instance_test.go'
  cluster-agent/utils/argocd_create.go
Labels: lgtm, approved

#708 GITOPSRVCE-787: wait X minutes before deleting orphaned SEB
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
  tests-e2e/appstudio/snapshotenvironmentbinding_test.go
Labels: lgtm, approved

#709 gitopsctl: fix timestamp parsing of non-splunk controller logs
  utilities/gitopsctl/implementations/parse-json-logs/parse-json-logs.go
Labels: approved

#706 Refactor backend db reconciler to return first error after processing resources, then verify no errors occur in unit tests
  backend/eventloop/db_reconciler.go
  backend/eventloop/db_reconciler_test.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
Labels: approved, do-not-merge/hold

#710 Add kubectl command to check controller deployments are ready
  scripts/openshiftci-presubmit-e2e-tests.sh
Labels: lgtm, approved

#716 docs: add ComparisonError and operationState to api.md
  docs/api.md
Labels: approved, do-not-merge/hold

#711 GITOPSRVCE-788: reconcile changes to repository Secrets
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_types.go
  backend-shared/util/util.go
  backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller.go
  backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller.go
  backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller_test.go
  backend/eventloop/db_reconciler_test.go
  backend/eventloop/repocred_reconciler.go
  backend/eventloop/repocred_reconciler_test.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential_test.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
  backend/eventloop/workspace_resource_event_loop.go
  backend/eventloop/workspace_resource_event_loop_test.go
  tests-e2e/appstudio/environment_test.go
  tests-e2e/core/privaterepo_test.go
  tests-e2e/core/queryscoped_cluster_secrets_test.go
  tests-e2e/fixture/gitopsdeploymentrepositorycredential/fixture.go
  tests-e2e/fixture/k8s/fixture.go
  tests-e2e/fixture/managedenvironment/fixture.go
Labels: lgtm, approved, do-not-merge/hold

#715 GITOPSRVCE-792: Light refactoring of DT/DTC/DTClaim controllers
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttarget_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttarget_controller_test.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetclaim_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetclaim_controller_test.go
  appstudio-controller/controllers/appstudio.redhat.com/predicates.go
  appstudio-controller/controllers/appstudio.redhat.com/predicates_dt.go
  appstudio-controller/controllers/appstudio.redhat.com/predicates_dt_test.go
  appstudio-controller/controllers/appstudio.redhat.com/predicates_test.go
  appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller_test.go
  appstudio-controller/controllers/appstudio.redhat.com/spacerequest_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/spacerequest_controller_test.go
  appstudio-controller/main.go
Labels: lgtm, approved, do-not-merge/hold

#717 GITOPSRVCE-793: document GitOps Service's self-healing mechanism
  backend/eventloop/cluster_reconciler.go
  backend/eventloop/db_reconciler.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  docs/self-healing-mechanism.md
Labels: approved, do-not-merge/hold

#724 feat: add sonar cloud properties for better control
  .sonarcloud.properties
Labels: lgtm
