Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-03, with the labels that each got.

#355 Chore: Get dev env working on cluster-bot hypershift (#417)
  manifests/scripts/openshift-argo-deploy/deploy.sh
  manifests/scripts/openshift-argo-deploy/openshift-gitops-subscription.yaml
Labels: lgtm, ok-to-test, approved

#373 Docker build issue on Mac Arm64 (#433)
  Makefile
Labels: lgtm, approved

#340 Security: namespace consistency of OperationCR with GitopsEngineInstance
  backend-shared/db/utils.go
  backend-shared/util/operations/types.go
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/db_reconciler_test.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_managed_env_test.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
  tests-e2e/core/operation_namespace_test.go
  tests-e2e/fixture/fixture.go
  tests-e2e/go.mod
Labels: lgtm, approved

#364 Remove unnecessary uses of GetOrCreateManagedEnvironmentByNamespaceUID, and add additional comments around its purpose
  backend-shared/db/util/utils.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/main.go
Labels: lgtm, approved

#376 GITOPSRVCE-449: update known bad values on stonesoup clusters, via init-container
  manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
  utilities/init-container/main.go
Labels: lgtm, approved

#342 Webhook implementation for CRs.
  appstudio-controller/config/default/manager_webhook_patch.yaml
  appstudio-controller/config/manager/manager.yaml
  appstudio-controller/config/webhook/manifests.yaml
  appstudio-controller/go.mod
  appstudio-controller/go.sum
  appstudio-controller/main.go
  manifests/base/crd/overlays/local-dev/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/kustomization.yaml
  manifests/overlays/k8s-env/kustomization.yaml
  tests-e2e/core/promotionrun_controller_test.go
  tests-e2e/core/webhook_test.go
  tests-e2e/go.mod
  tests-e2e/go.sum
Labels: lgtm, approved

#378 Fix kustomize error in appstudio-staging-cluster overlay
  appstudio-controller/config/default-no-prometheus/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/kustomization.yaml
  manifests/overlays/stonesoup-member-cluster/kustomization.yaml
Labels: approved

#368 Periodic clean-up for orphaned DB entries.
  backend-shared/db/application.go
  backend-shared/db/managedenvironment.go
  backend-shared/db/queries.go
  backend-shared/db/repo_cred.go
  backend-shared/db/syncoperation.go
  backend-shared/db/unreliable_db_client.go
  backend/eventloop/db_reconciler.go
  backend/eventloop/db_reconciler_test.go
  backend/go.mod
Labels: lgtm

#384 Temporarily disable deletion of ManagedEnviroment resources by database reconciler.
  backend/eventloop/db_reconciler.go
  backend/eventloop/db_reconciler_test.go
Labels: approved

#387 Don't include DB credentials in the connection err
  backend-shared/db/postgres-integration.go
Labels: lgtm

#388 ComponentDeploymentConditions test intermittently failing (#458)
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
Labels: lgtm

#371 Add Argo CD application status to gitops dashboard
  manifests/base/monitoring/grafana-dashboards/managed-gitops/gitops-dashboard.json
  manifests/base/monitoring/grafana-dashboards/stonesoup/gitops-dashboard.json
Labels: lgtm

#374 Add Argo CD Grafana dashboard for the GitOps Service instance
  manifests/base/monitoring/grafana-dashboards/managed-gitops/gitops-argocd-dashboard.json
  manifests/base/monitoring/grafana-dashboards/regenerate-stonesoup-dashboard.sh
  manifests/base/monitoring/grafana-dashboards/stonesoup/gitops-argocd-dashboard.json
Labels: lgtm

#389 Reduce log verbosity of backend and appstudio-controller components
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
  backend/eventloop/application_event_loop/application_event_runner.go
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/application_event_loop/application_event_runner_test.go
  manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml
Labels: lgtm, approved

#383 chore: remove deprecated getK8sClientForGitopsEngineInstance function
  backend/eventloop/application_event_loop/application_event_runner.go
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/application_event_loop/application_event_runner_deployments_test.go
  backend/eventloop/application_event_loop/application_event_runner_syncruns.go
  backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
  backend/eventloop/application_event_loop/application_event_runner_test.go
  backend/eventloop/application_event_loop/metrics_test.go
Labels: lgtm, approved

#400 Add read access Clusterrole(Binding) for CRD DeploymentTargetClass
  appstudio-controller/config/rbac/deploymenttargetclass_view_role.yaml
  appstudio-controller/config/rbac/deploymenttargetclass_view_role_binding.yaml
  appstudio-controller/config/rbac/kustomization.yaml
Labels: lgtm, approved

#381 chore: Update wait.Poll to wait.PollImmediate
  backend-shared/util/service_account.go
  backend/eventloop/eventloop_test_util/eventloop_test_util.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
  cluster-agent/utils/argocd_create.go
  utilities/load-test/loadtest/loadtest_test.go
Labels: lgtm, approved

#395 Remove unnecessary logging of SnapshotEnvBinding .status changes
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
Labels: lgtm, approved
