Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-07, with the labels that each got.

#499 Periodically clean up fix.
  backend/eventloop/db_reconciler.go
Labels: lgtm

#489 Add new database table ApplicationOwner
  .github/workflows/static.yml
  backend-shared/db/applicationowner.go
  backend-shared/db/applicationowner_test.go
  backend-shared/db/db_field_constants.go
  backend-shared/db/queries.go
  backend-shared/db/types.go
  backend-shared/db/unreliable_db_client.go
  backend-shared/db/utils.go
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/application_event_loop/application_event_runner_deployments_test.go
  backend/eventloop/db_reconciler.go
  backend/eventloop/db_reconciler_test.go
  db-schema.sql
  utilities/db-migration/migration_test/add_test_values/add_db_values.go
  utilities/db-migration/migration_test/add_test_values/add_db_values_test.go
  utilities/db-migration/migration_test/verify_test_values/verify_db_values_test.go
  utilities/db-migration/migrations/000014_v14.up.sql
  utilities/db-migration/migrations/000016_v16.down.sql
  utilities/db-migration/migrations/000016_v16.up.sql
Labels: lgtm, approved

#491 code refactoring for better performance.
  backend/eventloop/db_reconciler.go
Labels: lgtm, approved

#495 Add LogAPIResourceChangeEvent for DT/DTC/DTClaim code
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/devsandbox_deployment_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go
Labels: approved

#505 Don't log the contents of non-pointer Secret objects
  backend-shared/util/log/log.go
Labels: lgtm, approved

#533 Upgrade OpenShift Gitops version to 1.9
  manifests/scripts/openshift-argo-deploy/openshift-gitops-subscription.yaml
Labels: lgtm

#459 Add time series database metrics and grafana dashboard (#511)
  manifests/scripts/metrics-dashboard/postgresql/grafana-postgresql-exporter-dashboard-cm.yaml
  manifests/scripts/metrics-dashboard/postgresql/grafana-postgresql-exporter-dashboard.yaml
  manifests/scripts/metrics-dashboard/run.sh
Labels: lgtm, approved

#538 Rename ClusterRole/Bindings to prevent name clash with infra-deployments
  manifests/base/gitops-service-argocd/base/argo-cd-application-controller-clusterrole.yaml
  manifests/base/gitops-service-argocd/base/argo-cd-application-controller-clusterrolebinding.yaml
  manifests/base/gitops-service-argocd/base/argo-cd-server-clusterrole.yaml
  manifests/base/gitops-service-argocd/base/argo-cd-server-clusterrolebinding.yaml
Labels: approved

#501 Remove Argo CD dependency from backend component
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/go.mod
  backend/go.sum
Labels: lgtm

#500 Explicitly report cert authority invalid error
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
Labels: lgtm, approved

#496 Ensure we have database indexes the DB queries we are using (#561)
  backend-shared/db/apicrtodatabasemapping.go
  backend-shared/db/clusteraccess.go
  backend-shared/db/clusteruser.go
  backend-shared/db/deploymenttoapplicationmapping.go
  backend-shared/db/gitopsenginecluster.go
  backend-shared/db/operations.go
  db-schema.sql
  utilities/db-migration/migrations/000001_init_db.up.sql
  utilities/db-migration/migrations/000017_v17.down.sql
  utilities/db-migration/migrations/000017_v17.up.sql
Labels: lgtm, approved

#503 Add additional unit tests for the workspace event loop
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/workspace_event_loop.go
  backend/eventloop/workspace_event_loop_test.go
Labels: lgtm, approved

#536 Contribute my DeploymentTarget/Claim/Class 'step by step' doc to the repo
  docs/deployment-target-claim-class-steps.md
Labels: lgtm, approved

#539 Unnecessary Operations CRs/DBs are being created/cleaned (#659)
  backend-shared/util/fauxargocd/faux_argo_cd.go
Labels: lgtm
