Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-10, with the labels that each got.

#651 Refactor log statements to better use log context, reduce verbosity
  appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/devsandbox_deployment_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/snapshot_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_webhook.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_webhook.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_webhook.go
  backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentsyncrun_webhook.go
  backend-shared/db/test_utils.go
  backend-shared/util/log/log.go
  backend-shared/util/operations/types.go
  backend-shared/util/service_account.go
  backend-shared/util/util.go
  backend/eventloop/application_event_loop/application_event_loop.go
  backend/eventloop/application_event_loop/application_event_runner.go
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/application_event_loop/application_event_runner_syncruns.go
  backend/eventloop/cluster_reconciler.go
  backend/eventloop/controller_event_loop.go
  backend/eventloop/controller_event_loop_test.go
  backend/eventloop/db_metrics.go
  backend/eventloop/db_reconciler.go
  backend/eventloop/db_reconciler_test.go
  backend/eventloop/repocred_reconciler.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
  backend/eventloop/workspace_event_loop.go
  backend/eventloop/workspace_event_loop_test.go
  backend/eventloop/workspace_resource_event_loop.go
  backend/eventloop/workspace_resource_event_loop_test.go
  cluster-agent/controllers/argoproj.io/application_controller.go
  cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_cr_metrics.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
  cluster-agent/controllers/managed-gitops/eventloop/repocred.go
  cluster-agent/controllers/managed-gitops/operation_controller.go
  cluster-agent/controllers/util.go
  cluster-agent/controllers/util_test.go
  cluster-agent/controllers/utils_suite_test.go
  cluster-agent/metrics/argocd/argocd_metrics.go
  cluster-agent/utils/argocd_login_credentials.go
  cluster-agent/utils/argocd_terminate_app_command.go
  tests-e2e/fixture/environment/fixture.go
Labels: lgtm, approved

#661 Enable AppProject isolation for Makefile run targets
  backend/Makefile
  cluster-agent/Makefile
Labels: lgtm, approved

#662 Disable Environment webhook
  appstudio-controller/config/webhook/manifests.yaml
Labels: approved

#638 Recreate missing Secrets for ManagedEnvironments.
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
Labels: lgtm, approved

#614 Unit tests for waitForOperationToComplete, isOperationComplete (#688)
  backend-shared/util/operations/types.go
  backend-shared/util/operations/types_test.go
Labels: lgtm, approved

#665 Fix failing of DT e2e test
  tests-e2e/appstudio/dt_dtc_dtclass_test.go
Labels: lgtm, approved

#676 GITOPSRVCE-767: fix interimittent failure in workspace_resource_event_loop_test.go
  backend/eventloop/workspace_resource_event_loop_test.go
Labels: lgtm, approved

#677 GITOPSRVCE-771: add temp overlays for debugging env webhook
  appstudio-controller/config/tmp-default-webhook-with-env/kustomization.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/manager_auth_proxy_patch.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/manager_config_patch.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/manager_webhook_patch.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/webhookcainjection_patch.yaml
  appstudio-controller/config/tmp-webhook-with-env/kustomization.yaml
  appstudio-controller/config/tmp-webhook-with-env/kustomizeconfig.yaml
  appstudio-controller/config/tmp-webhook-with-env/manifests.yaml
  appstudio-controller/config/tmp-webhook-with-env/service.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/appstudio-controller-deployment-patch.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/backend-deployment-patch.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/cluster-agent-deployment-patch.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/kustomization.yaml
Labels: approved

#679 GITOPSRVCE-771: re-enable environment webhook
  appstudio-controller/config/webhook/manifests.yaml
Labels: approved

#682 GITOPSRVCE-778: only create operations for missing external cluster secrets
  backend-shared/db/clusteraccess_test.go
  backend-shared/db/clustercredentials.go
  backend-shared/db/gitopsenginecluster_test.go
  backend-shared/db/gitopsengineinstance_test.go
  backend-shared/db/guardrow_test.go
  backend-shared/db/injection_test.go
  backend-shared/db/managedenvironment_test.go
  backend-shared/db/test_utils.go
  backend-shared/db/types_test.go
  backend-shared/db/util/utils.go
  backend-shared/db/util/utils_test.go
  backend/eventloop/application_event_loop/application_event_runner_test.go
  backend/eventloop/db_reconciler_test.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
  cluster-agent/controllers/argoproj.io/application_controller_test.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
  utilities/db-migration/migration_test/add_test_values/add_db_values.go
Labels: lgtm, approved

#678 GITOPSRVCE-772: fix intermittent E2E test failure in gitopsdeployment_test.go
  tests-e2e/fixture/appproject/fixture.go
Labels: lgtm, approved

#683 GITOPSRVCE-731: add server name to DB TLS conn info
  backend-shared/db/postgres-integration.go
Labels: approved

#685 GITOPSRVCE-723: Better secure dev postgresql instance
  manifests/base/postgresql-staging/postgresql-staging.yaml
Labels: lgtm, approved

#686 GITOPSRVCE-731: add InsecureSkipVerify to postgresql connection settings
  backend-shared/db/postgres-integration.go
Labels: approved

#690 Fix invalid SEVERE log entry by only checking field (rather than pointer) of event.Message.Event in app event loop
  backend/eventloop/application_event_loop/application_event_loop.go
  backend/eventloop/eventlooptypes/types.go
  backend/eventloop/eventlooptypes/types_test.go
  cluster-agent/controllers/managed-gitops/operation_controller.go
Labels: approved

#692 Fix log keys in application_event_loop.go
  backend/eventloop/application_event_loop/application_event_loop.go
Labels: approved

#684 Remove unused router code
  backend/go.mod
  backend/main.go
  backend/main_test.go
  backend/routes/router.go
  backend/routes/webhooks/webhooks.go
Labels: lgtm

#656 Add mocks in MakeFile for generating mocks
  .github/workflows/static.yml
  Makefile
  backend-shared/Makefile
  backend/Makefile
  backend/condition/mocks/conditions.go
  cluster-agent/Makefile
  cluster-agent/utils/mocks/ApplicationServiceClient.go
  cluster-agent/utils/mocks/Client.go
  cluster-agent/utils/mocks/SessionServiceClient.go
  cluster-agent/utils/mocks/SettingsServiceClient.go
  cluster-agent/utils/mocks/VersionServiceClient.go
Labels: lgtm, approved

#693 GITOPSRVCE-771: remove temporary overlays added for debugging
  appstudio-controller/config/tmp-default-webhook-with-env/kustomization.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/manager_auth_proxy_patch.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/manager_config_patch.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/manager_webhook_patch.yaml
  appstudio-controller/config/tmp-default-webhook-with-env/webhookcainjection_patch.yaml
  appstudio-controller/config/tmp-webhook-with-env/kustomization.yaml
  appstudio-controller/config/tmp-webhook-with-env/kustomizeconfig.yaml
  appstudio-controller/config/tmp-webhook-with-env/manifests.yaml
  appstudio-controller/config/tmp-webhook-with-env/service.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/appstudio-controller-deployment-patch.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/backend-deployment-patch.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/cluster-agent-deployment-patch.yaml
  manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/kustomization.yaml
Labels: approved

#666 Recreate missing Secrets for RepositoryCredentials.
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
Labels: lgtm, approved

#695 Move up to latest kube-rbac-proxy, and add -http2-disable=true
  appstudio-controller/config/default-no-webhook/manager_auth_proxy_patch.yaml
  appstudio-controller/config/default/manager_auth_proxy_patch.yaml
  backend/config/default/manager_auth_proxy_patch.yaml
  cluster-agent/config/default/manager_auth_proxy_patch.yaml
  manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
  manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml
Labels: approved

#691 GITOPSRVCE-783: use Component CR .metadata.Name, not ComponentName
  appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller_test.go
Labels: lgtm, approved

#689 Add additional DB unit tests
  backend-shared/db/apicrtodatabasemapping_test.go
  backend-shared/db/app_project_repository_test.go
  backend-shared/db/application_test.go
  backend-shared/db/syncoperation.go
  backend-shared/db/syncoperation_test.go
Labels: lgtm, approved

#696 GITOPSRVCE-731: Add Amazon CA root certs, re-enable TLS verification
  Dockerfile
  backend-shared/db/postgres-integration.go
Labels: approved

#697 Move webhooks to GitOps-Service.
  appstudio-controller/config/default-no-prometheus/kustomization.yaml
  appstudio-controller/config/default-no-prometheus/webhookcainjection_patch.yaml
  appstudio-controller/config/default/kustomization.yaml
  appstudio-controller/config/webhook/manifests.yaml
  appstudio-controller/controllers/webhooks/environment_webhook.go
  appstudio-controller/controllers/webhooks/environment_webhook_unit_test.go
  appstudio-controller/controllers/webhooks/promotionrun_webhook.go
  appstudio-controller/controllers/webhooks/promotionrun_webhook_test.go
  appstudio-controller/controllers/webhooks/snapshot_webhook unit_test.go
  appstudio-controller/controllers/webhooks/snapshot_webhook.go
  appstudio-controller/controllers/webhooks/snapshotenvironmentbinding_webhook.go
  appstudio-controller/controllers/webhooks/snapshotenvironmentbinding_webhook_test.go
  appstudio-controller/controllers/webhooks/webhooks.go
  appstudio-controller/go.mod
  appstudio-controller/go.sum
  appstudio-controller/main.go
  tests-e2e/appstudio/dt_dtc_dtclass_test.go
  tests-e2e/appstudio/environment_test.go
  tests-e2e/appstudio/promotionrun_controller_test.go
  tests-e2e/appstudio/snapshotenvironmentbinding_test.go
  tests-e2e/appstudio/webhook_test.go
  tests-e2e/go.mod
  tests-e2e/go.sum
  utilities/load-test/go.mod
  utilities/load-test/go.sum
Labels: lgtm, approved
