Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-01, with the labels that each got.

#292 update module name in db-migration
  utilities/db-migration/go.mod
  utilities/db-migration/main.go
Labels: lgtm, needs-ok-to-test

#293 update backend deps
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: lgtm, needs-ok-to-test

#294 Remove all uses of metadata.Namespace field of Namespace resources
  backend-shared/util/tests/types_test_util.go
  backend/eventloop/application_event_loop/application_event_runner.go
  backend/eventloop/application_event_loop/application_event_runner_deployments.go
  backend/eventloop/application_event_loop/application_event_runner_syncruns.go
  backend/eventloop/eventlooptypes/types_test.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/workspace_event_loop_test.go
  backend/eventloop/workspace_resource_event_loop.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
  cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
  cluster-agent/utils/argocd_login_credentials_test.go
  cluster-agent/utils/argocd_sync_command.go
  cluster-agent/utils/argocd_sync_command_test.go
  cluster-agent/utils/argocd_terminate_app_command_test.go
Labels: lgtm, approved

#286 Add docs for ArgoCD bump
  docs/bump_argocd.md
Labels: lgtm

#298 Update OWNERs file
  OWNERS
Labels: approved

#285 Delete top-level resources first as part of e2e cleanup
  tests-e2e/fixture/fixture.go
Labels: lgtm

#299 Validate syncing with Automated sync policy
  backend/eventloop/application_event_loop/application_event_runner_syncruns.go
  backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
  backend/eventloop/application_event_loop/application_event_runner_test.go
Labels: lgtm

#303 Update push.yaml to support new kustomize repository URL format
  .tekton/push.yaml
Labels: lgtm, approved

#309 Patch backend component on stonesoup cluster: restore controller limits to original values
  backend/config/default/manager_auth_proxy_patch.yaml
  backend/config/manager/manager.yaml
Labels: approved

#302 Sanitize messages for managed environment connection status
  backend-shared/util/gitopserrors/gitops_errors.go
  backend/eventloop/shared_resource_loop/sharedresourceloop.go
  backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
Labels: lgtm

#316 Fix changes missed in db folder move
  cluster-agent/controllers/util.go
  cluster-agent/controllers/util_test.go
Labels: lgtm

#317 Add Stonesoup-specific Prometheus YAML
  appstudio-controller/config/default-no-webhook-no-prometheus/kustomization.yaml
  backend/config/default-no-prometheus/kustomization.yaml
  cluster-agent/config/default-no-prometheus/.gitignore
  cluster-agent/config/default-no-prometheus/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
  manifests/overlays/appstudio-staging-cluster/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/appstudio-controller/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/appstudio-controller/service-monitor.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/appstudio-controller/service.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/backend/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/backend/service-monitor.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/backend/service.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/cluster-agent/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/cluster-agent/service-monitor.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/cluster-agent/service.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/kustomization.yaml
Labels: approved

#312 Fix continual increment of deployment failures metric
  backend/metrics/metrics.go
  backend/metrics/metrics_test.go
Labels: lgtm

#313 Add initial Grafana dashboard
  manifests/grafana/gitops-dashboard.json
Labels: lgtm

#320 Disable Stonesoup-specific ServiceMonitors, move them to infra-deployments
  manifests/overlays/appstudio-staging-cluster/prometheus/appstudio-controller/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/backend/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/prometheus/cluster-agent/kustomization.yaml
Labels: approved

#321 Add RBAC to allow controllers to create TokenReviews, add missing appstudio-controller deployment patch
  appstudio-controller/config/rbac/kustomization.yaml
  backend/config/rbac/kustomization.yaml
  cluster-agent/config/rbac/kustomization.yaml
  manifests/overlays/appstudio-staging-cluster/kustomization.yaml
Labels: approved

#325 Move dashboard into base/monitoring, add ConfigMap generator for Stonesoup
  manifests/base/monitoring/base/grafana-dashboards/gitops-dashboard.json
  manifests/base/monitoring/base/kustomization.yaml
Labels: approved

#295 Sync main and service-first branch using Github Action
  .github/workflows/sync-branch.yml
Labels: lgtm

#311 Periodic job to clean up orphan secrets from cluster.
  backend-shared/db/gitopsengineinstance.go
  backend-shared/db/gitopsengineinstance_test.go
  backend-shared/db/queries.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
Labels: lgtm
