Repository redhat-appstudio/managed-gitops, pull requests merged in 2023-06, with the labels that each got.

#478 Remove DTClass from appstudio-e2e tests overlay
  manifests/overlays/appstudio-staging-cluster/kustomization.yaml
Labels: approved

#483 Temporarily remove environment webhook
  appstudio-controller/config/webhook/manifests.yaml
Labels: approved

#473 Remove time.Sleep() and replace it with mocked time
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller_test.go
  appstudio-controller/main.go
  backend-shared/util/time.go
Labels: lgtm

#481 Move handle deployment modified tests to application_event_runner_test.go file
  backend/eventloop/application_event_loop/application_event_runner_deployments_test.go
  backend/eventloop/application_event_loop/application_event_runner_test.go
Labels: lgtm, approved

#464 Delete GitOpsDeploymentManagedEnvironment when the corresponding Environment resource is deleted
  appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
  appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
  tests-e2e/core/managed_environment_test.go
Labels: lgtm, approved

#475 clean up job logging.
  backend-shared/util/util.go
  backend/eventloop/db_reconciler.go
  cluster-agent/controllers/argoproj.io/namespace_reconciler.go
Labels: lgtm, approved

#480 chore: E2E refactoring.
  backend/eventloop/application_event_loop/application_event_runner.go
  tests-e2e/core/environment_test.go
  tests-e2e/core/managed_environment_test.go
Labels: lgtm, approved

#484 Restrict LogAPIResourceChangeEvent log contents (#593)
  backend-shared/util/log/log.go
Labels: lgtm, approved

#488 Ignore mocks and generated files in codecov.yml
  .codecov.yml
Labels: approved

#493 Remove datasources from Grafana dashboards
  manifests/base/monitoring/grafana-dashboards-new/gitops-argocd-dashboard.json
  manifests/base/monitoring/grafana-dashboards-new/gitops-dashboard.json
  manifests/base/monitoring/grafana-dashboards-new/kustomization.yaml
Labels: approved

#494 Remove generatorOptions as it prevents dashboard refresh in RHTAP
  manifests/base/monitoring/grafana-dashboards-new/kustomization.yaml
Labels: approved
